### ISSUE TITLE
Add security precautions

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#11]
`cpu-energy-meter` needs additional privileges, and thus should be careful to not let them be exploited. While this is highly unlikely given that the tool has almost no user interaction, we should still follow best practices.

This includes dropping privileges after we don't need them anymore. For example, after #10 is implemented, we should be able to [drop the privileges](http://etutorials.org/Programming/secure+programming/Chapter+1.+Safe+Initialization/1.3+Dropping+Privileges+in+setuid+Programs/) for opening the device files after the initialization phase. We might even be able to use [seccomp](https://en.wikipedia.org/wiki/Seccomp) to restrict the process to only a few specific syscalls after the initialization phase.

**Comment by TBunk** [comment]
The provided link is no longer available, though, the topic is well documented [here](https://www.safaribooksonline.com/library/view/secure-programming-cookbook/0596003943/ch01s03.html).

I've implemented it in commit 61b695baf3edeed6654648fa9bfacf1a948debb4, though, due to the nature of the methods getgid(), getuid(), etc., this only works when invoking the program without root privileges. However, once issue #7 is implemented, this problem would practically be resolved by itself.

**Comment by PhilippWendler** [comment]
If I understand this correctly, we could change to `nobody`/`nogroup` (numeric id 65534), right?

**Comment by TBunk** [comment]
As discussed today, the gid and uid is now set to `nobody`/ `nogroup`. The changes were made in commit da9746f0a91247fc45ecbdd974cba7dd3794985e.
