### ISSUE TITLE
SIGINT problems

### ISSUE THREAD

**Issue by antondalgren** [sosy-lab/cpu-energy-meter#22]
Hi

I'm using this tool to measure the energy usage of the CPU in benchmark suite. I'm having trouble to send the `SIGINT` signal to the process. 

Im using python3 for this and both running the multiprocessing module and the subprocess module as seen below. 
````
def start_CPU_measure():
  print(" -------- Starting CPU measure ----------")
  p = multiprocessing.Process(target=worker, args=( ))
  p.start()
  print(" -------- Done with CPU measure ----------")

def worker():
  measure_process = subprocess.Popen(args=["cpu-energy-meter", "-d"], shell=True)
  time.sleep(5)
  measure_process.send_signal(signal.SIGINT)
```` 

Do you have any suggestions on how to get this `SIGINT` to actually get through?

**Comment by PhilippWendler** [comment]
The problem is `shell=True`. Python spawns a shell, which then spawns `cpu-energy-meter`, and the signal is sent to the shell instead of `cpu-energy-meter`. Without this, it works.

In general, one should avoid `shell=True` anyway for [security reasons](https://docs.python.org/3/library/subprocess.html#security-considerations).

Note that if you call `cpu-energy-meter` from another process and want to parse its arguments, make sure to pass `-r` (and not `-d`).

**Comment by antondalgren** [comment]
@PhilippWendler Yes thats it, thanks alot!
