### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#9]
The code base still contains a lot of old code that is now unused, and should be removed. Probably there could also be some refactorings that simplify the remaining code then.

**Comment by TBunk** [comment]
@PhilippWendler I'd deem the code quality in a pretty good state right now. I've removed nearly all of the unused code in previous commits (e.g., see commit bd08d71ee7b86b492faedfe22d78fcd59599b69a and aa70eadfe0ef00976d64ac73d4540385a1c69371), with some deliberate exceptions. The excessive use of error-values (int) as returning values seems a bit odd to me, though it is well and consistently coded, and working as intended (i.e., nothing that needs to be refactored imo).

The only thing left to do would be the use of a code formatter for a consistent code base. Do you agree with me here? I would use the linux kernel code style format (see https://www.kernel.org/doc/html/v4.10/    process/coding-style.html), because afaik that's the format that the code was previously based on (partially, at least).

**Comment by PhilippWendler** [comment]
I don't like the kernel coding style very much (indentation is 8 spaces). If the code is only a little bit inconsistent, we could keep it and just improve new and changed code. But if you want, you can of course also reformat it. I just would prefer to keep indentation at 2 spaces.

**Comment by TBunk** [comment]
The code was formatted in #17 . For reference, I've used clang with a `.clang-format` file that contained the following specifications:
  BasedOnStyle: LLVM
  IndentWidth: 2
  UseTab: Never
  BreakBeforeBraces: Attach
  AllowShortIfStatementsOnASingleLine: false
  AllowShortLoopsOnASingleLine: false
  AllowShortFunctionsOnASingleLine: false
  IndentCaseLabels: false
  ColumnLimit: 100
